### ISSUE TITLE
Changing the profile failing

### ISSUE THREAD

**Issue by kucjac** [slimbook/slimbookamdcontroller#7]
The `slimbookamdcontroller` v0.3.2 installed in the Ubuntu 21.04 from the `apt ppa:slimbook/slimbook` repository, was working properly.
But suddenly, after some updates, it started to fail. 

The indicator icon disappeared, and it was not starting at startup.

I've tried to set it up again, but the accept button looked like it's inactive. 
I've then checked the terminal logs and the following error occurs while clicking on the `ACCEPT` button.

I've checked the logs in the terminal, and I've obtained the following messages:
```python
Traceback (most recent call last):
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 491, in on_btnAceptar_clicked
    print(str(self.parameters[mode].split('-')))
IndexError: list index out of range
['']
Traceback (most recent call last):
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 494, in on_btnAceptar_clicked
    print('Updating '+self.modo_actual+' to : '+set_parameters[0]+' '+set_parameters[1]+' '+set_parameters[2]+'.\n')
IndexError: list index out of range
Traceback (most recent call last):
```

I really like how AMD controller was working. 
Do you think it is a matter of my OS or rather some application issue? 
If somehow I can help you, just let me know If I can provide you more logs or contribute in this PR.

**Comment by UbayGD** [comment]
Hi @kucjac !

I have been testing and get the same error. 

The parameter list is coming up empty. From what I was looking at, in the "inicio" function it should read them from the "slimbookamdcontroller.conf" file but on checking it I noticed that "cpu-parameters" has no value (at least in my case).

If that key should be populated with the user CPU parameters, that's where the problem is.

I will try to take a look tomorrow with more time.

Thanks!!

**Comment by slimbook** [comment]
That might be because we updated configuration files, and now, your processor is not in the list of available processors, try the new release and test  it. Thank you!

**Comment by kucjac** [comment]
@slimbook thanks a lot. Right now, everything works as expected. :+1:
